SAA docs tweaks (#4482)
* Use the same activity ID

* Remove logging since it doesn't compile given page code

/tmp/dotnet-logger-repro/Worker cat Program.cs
using Microsoft.Extensions.Logging;
using Temporalio.Client;
using Temporalio.Common.EnvConfig;
using Temporalio.Worker;

var connectOptions = ClientEnvConfig.LoadClientConnectOptions();
connectOptions.TargetHost ??= "localhost:7233";
connectOptions.LoggerFactory = LoggerFactory.Create(builder =>
    builder.
        AddSimpleConsole(options => options.TimestampFormat = "[HH:mm:ss] ").
        SetMinimumLevel(LogLevel.Information));
var client = await TemporalClient.ConnectAsync(connectOptions);
/tmp/dotnet-logger-repro/Worker dotnet build
MSBuild version 17.8.49+7806cbf7b for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/private/tmp/dotnet-logger-repro/Worker/Program.cs(8,32): error CS0103: The name 'LoggerFactory' does not exist in the current context [/private/tmp/dotnet-logger-repro/Worker/Worker.csproj]

Build FAILED.

/private/tmp/dotnet-logger-repro/Worker/Program.cs(8,32): error CS0103: The name 'LoggerFactory' does not exist in the current context [/private/tmp/dotnet-logger-repro/Worker/Worker.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.64

* revert dotnet changes

---------

Co-authored-by: Andrew Yuan <Andrew.Yuan@temporal.io>
Co-authored-by: Milecia McG <47196133+flippedcoder@users.noreply.github.com>